apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-postgres-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-postgres-sa
roleRef:
  kind: Role
  name: {{ .Release.Name }}-postgres-role
  apiGroup: rbac.authorization.k8s.io
