apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-secret
type: Opaque
data:
  postgres-username: {{ .Values.postgresql.username | b64enc | quote }}
  postgres-password: {{ .Values.postgresql.password | b64enc | quote }}