appVersion: "13.3"  # Specify the PostgreSQL version here
postgresql:
 database: "my_database"  # The name of the database to create
 username: "myuser"  # PostgreSQL username
 password: "mypassword"  # PostgreSQL password